# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://github.com/cginternals/typescript-init' # the base hostname & protocol for your site

title: 'fiblib'
author: 'Daniel Limberger'

languages: [ 'en' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'vendor',
  '.jekyll-metadata']

keep_files: [
  'doc',
  'test-results',
  'js/fiblib.js',
  'js/fiblib.min.js',
  'js/fiblib.js.map']

# CSS Minification
sass:
  style: compressed
  